### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by daun** [swup/fragment-plugin#15]
Looks like I can't update the repo description. @hirasso could you do that? Quoting the suggestion from the [issue for updated plugin descriptions](https://github.com/swup/swup/issues/721):

> A swup plugin for replacing dynamic fragments

Feel free to change as you see fit. It should be identical across these three files:

- [x] GitHub repo description
- [x] Package.json description
- [x] Readme tagline

**Comment by hirasso** [comment]
Thanks @daun ! Done.
