### ISSUE TITLE
Case for one-directional matching: closing popup to different-than-last URL

### ISSUE THREAD

**Issue by daun** [swup/fragment-plugin#3]
**Description of the issue**

Closing the popup to a different filtered list than the one it was opened from requires replacing both the overlay and the list fragment.

Is this a case where we need one-directional matching only?

Open popup: replace overlay
Close popup: replace overlay and list, in case we're loading a different list than the currently shown one

**How to reproduce the issue**

- Open the [demo](https://swup.fragment-plugin.rassohilber.com/)
- Click on `Mechanics`
- Click on `Princesses`
- Click on `Princess Peach`
- Right-click browser back-button, then click on `Filter: Mechanics`

This currently replaces only the overlay container, closing the popup. The list itself is stuck in `Princesses`, though. However, since we're going to a new filtered list than the one we opened it from, it should also replace the list container. When opening the popup, we want to keep the currently filtered list, but when closing, we want to update the list as well.

**Comment by daun** [comment]
I've stumbled upon the meeting notes of a previous call, and this is what we came up with:

|from → to|replace|condition|
| ---- | ------- | ------- |
| list → list | list | — |
| list → detail | detail | — |
| detail → list | detail | new list url == previous list url |
| detail → list | list + detail | new list url != previous list url |

Combining the last two and removing the condition would also work, it was just for grokking the logic.

**Comment by hirasso** [comment]
Interesting. This is indeed still a Limitation of the plugin, great find! The one-directional route could be a last-resort solution for that scenario, but I would love to solve this in a more general and elegant way. Need to think about it.

**Comment by daun** [comment]
I would consider one-way matching the general, elegant solution here. It's expressive, it's self-documenting, and it matches the problem domain.

But yeah, let's keep an open tab here. Plenty of time to get this right 🥨

**Comment by daun** [comment]
Solved 🦜
