### ISSUE TITLE
Allow default scrolling behavior on fragment visits

### ISSUE THREAD

**Issue by daun** [swup/fragment-plugin#34]
**Describe the problem**

- Currently, the plugin will disable the scroll reset for any fragment visit
- There's certain scenarios where you'd still want the default scroll behavior: pagination or filters below the content

**Describe the proposed solution**

- Add a `scroll` option to fragment rules

**Alternatives considered**

- Hooking after the plugin and manually setting `visit.scroll.reset = true;`
- It's preferable to have an official API as it might be quite a common thing for people to try to achieve

**How important is this feature to you?**

- [ ] Nice to have
- [x] Would make my life a lot easier
- [ ] I cannot use swup without it

**Comment by hirasso** [comment]
Sounds great! And should be easily achievable. Another name for the rule option could `preserveScroll` with a default of `true`, to keep defaults to positive values.

**Comment by daun** [comment]
What about allowing a fragment id `#list` as a value of the scroll option? Some fragment visits might require scrolling to a specific element, e.g. the result list of a filter UI.

**Comment by hirasso** [comment]
Interesting idea! But I feel like we should leave this to the implementors. With the simplification of the fragmentVisit object it would be very simple to implement custom logic:

```ts
swup.hooks.on('content:replace', async (visit) => {
  if (visit.fragmentVisit?.name === 'my-fragment-visit') {
    visit.scroll.reset = true;
  }
});
```

or 

```ts
swup.hooks.on('content:replace', async (visit) => {
  if (visit.fragmentVisit?.name === 'my-fragment-visit') {
    visit.scroll.target = '#list';
  }
});
```
Do you think we still need this as an option then?

**Comment by hirasso** [comment]
If we go with a new rule option, is this what you were imagining?

```js
{
  scroll: boolean | string
}
```

Where `scroll` would be `false` for each rule if not customized. Options would be 

1. scroll to the top if the rule matches:

```js
{
  scroll: true
}
```

2. scroll to the first matching element if the rule matches:

```js
{
  scroll: '#list'
}
```
