### ISSUE TITLE
Reverse route matching priority: select first matched route

### ISSUE THREAD

**Issue by daun** [swup/fragment-plugin#4]
**Describe the problem**

Somehow, matching routes from the back didn't feel right to me. I've had a look at some frameworks I've used in the past and all of them seem to go with the first matched route. I think we should do the same — it's a common pattern and expected by users.

The best reason (besides current practice) is catch-all routes: fallback routes like `*` are always defined last.

A few examples:

- [Vue Router](https://v3.router.vuejs.org/guide/essentials/dynamic-matching.html#matching-priority): "the earlier a route is defined, the higher priority it gets"
- [Svelte SPA Router](https://github.com/ItalyPaleAle/svelte-spa-router#define-your-routes): "the first matching path will determine which route to load"
- [Laravel](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteCollection.php#L145): "find the first route matching a given request"
- [Ruby on Rails](https://stackoverflow.com/a/21003394): "routes defined first take higher precedence over the ones listed later"

Counter-examples:

- Express.js: "calculates the priority of a route based on the specificity of its path" (very messy)

**Describe the proposed solution**

- Use `find` instead of `findLast`

**How important is this feature to you?**

- [x] Would make me feel much better as we're using established patterns

**Comment by hirasso** [comment]
You are totally right, let's switch to `find`! Poor JS Plugin  😪😄

**Comment by daun** [comment]
Solved 🦆
