### ISSUE TITLE
Allow to customize the pathToRegexp options per rule

### ISSUE THREAD

**Issue by hirasso** [swup/fragment-plugin#5]
**Describe the problem**

On large websites, it might be tedious to define all rules for fragments for every last possible route. For example, there might be multiple filterable lists cluttered throughout a nested (and possibly hard to predict) URL structure.

**Describe the proposed solution**

Every `rule` should accept an additional options object `matchOptions`, that acts as a thin wrapper around (or a proxy for?) the [options](https://github.com/pillarjs/path-to-regexp#path-to-regexp-1) of the underlying library `pathToRegexp`. Right now, the most useful of the options seems to be `start`. Setting that option to false would allow to ignore everything before a certain URL part. 

`\\?filter=:filter` would match all of the following with `start` set to `false`:

- `/?filter=my-filter`
- `/my-path?filter=my-filter`
- `/my-path/?filter=my-filter`
- `/my-path/my-subpath/?filter=my-filter`

**Questions**

- Should we pass all options through to `pathToRegexp` or should we hand-pick a few of them, and maybe even rename them?

**Comment by daun** [comment]
I'd suggest only passing those options through. Proxying or modifying sounds like quite the burden for maintaining and documenting the options.

Re: your specific usecase -- couldn't this easily be solved using a wildcard `(*)` in the beginning of the pattern?

**Comment by hirasso** [comment]
Uuugh! You might be right. The wildcard would of course be much better! I'll leave it untouched for now. We can still implement it when we really know if we need it.
