### ISSUE TITLE
[Bug]: Cannot find package @swup/fragment-plugin@1

### ISSUE THREAD

**Issue by ish91** [swup/fragment-plugin#67]
### What did you expect? 🧐

This should include the minified production file from a CDN:
<script src="https://unpkg.com/@swup/fragment-plugin@1"></script>

### What actually happened? 😵‍💫

fragment-plugin@1 is not available

### Swup and plugin versions 📝

- swup: 4

### What browsers are you seeing the problem on? 🧭

Chrome

### URL to minimal reproduction 🔗

https://unpkg.com/@swup/fragment-plugin@1

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
There's no v1 (yet). If you swap out the 1 for a 0, it should work. We'll need to update the readme example at some point 🌝

**Comment by hirasso** [comment]
OR we fast-foward to 1.0.0 🏎️💨 I'm using it in production already, after all.

**Comment by daun** [comment]
Let's upgrade to v1! I'm using it in production as well and it'd be a good signal for users that they're working with production ready tech 🚀

**Comment by hirasso** [comment]
Altight! First todo for tomorrow ☠️

**Comment by hirasso** [comment]
Actually ... why wait? #69

**Comment by hirasso** [comment]
@ish91 So – you should change your CDN-link back to [`@1`](https://unpkg.com/@swup/fragment-plugin@1) – we just released the first production-ready version 🙂
