### ISSUE TITLE
Think through what should happen if all fragments in a visit already match the new URL

### ISSUE THREAD

**Issue by hirasso** [swup/fragment-plugin#80]
### Describe the problem 🧐

If all fragments in a visit already match `visit.to.url`, currently the matching fragment visit will simply be ignored, falling back to swups default containers for that visit. 

That is not what would be expected. That kind of situation is basically like a link to the current page, even though the `visit.from.url` is not equal to `visit.to.url`. 

### Describe the propsed solution 😎

I've done a bit of research in #79 and then decided to first start with an issue.

I'm unsure about the ideal solution for the scenario described above. Maybe the behavior could be aligned with whatever is defined in `swup.options.linkToSelf`:

- if `linkToSelf` is `scroll`, nothing should happen (matching fragment visit, empty `containers`)
- if `linkToSelf` is set to `navigate`, the fragments should be reloaded (matching fragment visit with the containers of the matched rule)

As mentioned above, I'm not absolutely sure about the perfect solution here. Happy to talk it all through together.

### Alternatives considered 🤔

Add a hook and always remove the fragment URL from the fragment element:

```ts
/** allow details to always be replaced */
swup.hooks.on("visit:end", () => {
  const detail = $<FragmentElement>("#detail")!;
  detail.__swupFragment!.url = "";
});
```

### How important is this feature to you? 🧭

Would make my life a lot easier

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
@hirasso Did the changes in #79 resolve this? Or is it still a thing?

**Comment by hirasso** [comment]
Yes, this was resolved. Take a look at https://filter-munich.com/calendar/ and click one of the items on the left multiple times. It will reload the fragment on the right, as that fragment already matches the current URL.

**Comment by daun** [comment]
@hirasso Nice. How does it know to only reload the right-hand fragment, and not all of them?

**Comment by daun** [comment]
Ah, true!

**Comment by hirasso** [comment]
Thanks for reminding me to close this as completed :)
